apiVersion: v1
kind: Service
metadata:
    name: goca-service
    labels:
        app: goca-service
spec:
    type: NodePort
    ports:
    - port: 8112
      protocol: TCP
      targetPort: 8112
    selector:
        run: goca
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: goca-deployment
spec:
    selector:
        matchLabels:
            run: goca
    replicas: 1
    template:
        metadata:
            labels:
                run: goca
        spec:
            containers:
            - name: goca
              image: docker.io/jackyzhangfd/goca:1.0
              imagePullPolicy: Always
              ports:
              - containerPort: 8112